server:
    host: '0.0.0.0'
    port: 8080
    debug: True
    environment: development
    testing: False
    use_reloader: True

api:
    specs:
        - path: api/pubgrade-sidecar.yaml
          path_out: /app/app/config/pubgrade-sidecar.modified.yaml
          append: null
          add_operation_fields:
              x-openapi-router-controller:  pubgrade-sidecar.controllers
          connexion:
              strict_validation: True
              validate_responses: False
              options:
                  swagger_ui: True
                  serve_spec: True

environments:
    secrets:
        access_token: "Access@123"
