name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Push the Docker image
      run: docker buildx build . --file Dockerfile --tag lvarin/pubgrade-sidecar:$(date +%Y%m%d-%H%M%S) --push
