name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log into registry ${{ secrets.DOCKER_REGISTRY }} 
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and Push the Docker image
      run: docker buildx build . --file Dockerfile --tag ${{ secrets.DOCKER_REGISTRY }}/lvarin/pubgrade-sidecar:$(date +%Y%m%d%H%M%S) --push
